# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OmrGvL2q3qtG_8_fToiLaKyIca_TUqE
"""

print ('Dia berkata : "Pergilah"')

print ("Aku menimpali:\"Apakah  kau ingin aku 'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/)")

