# -*- coding: utf-8 -*-
"""Praktikum2-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u16kVoN3b1bB615gyyzoBpE3vhOpOkZe

Nama: Linda Ovi Rahayu

NPM: 2411012044
"""

# Operasi in pada string
berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan \ teks editor masa kini seperti Visual Studio Code, \ atom, sublime text, dan lain sebagainya'

print('sublime text' in berita) # output: True
print('notepad++' in berita) # output: False

# Memotong String
nama = 'Lendis Fabri'
print(nama[4]) # output: i
print(nama[7]) # output: F
print(nama[-1]) # output: i
print(nama[-3]) # output: b

# Slicing String
judul = 'Pelajaran Matematika Untuk SD'

print(judul[0:5]) # output: Pelaj
print(judul[:10]) # output: Pelajaran
print(judul[10:15]) # output: Matem
print(judul[-1:-3]) # output:
print(judul[:-3]) # output: Pelajaran Matematika Untuk
print(judul[-5:]) # output: uk SD

# Menghitung Panjang String
print(len('Indonesia')) # output: 9
print(len('Malaysia')) # output: 8

# Memeriksa Karakter Awal String
nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara)) # False
print(nomor_telepon_2.startswith(kode_negara)) # False
print(nomor_telepon_3.startswith(kode_negara)) # True

# Memeriksa Karakter Akhir String
email_1 = 'presiden@gmail.com'
email_2 = 'preseden@outlook.com'

print(email_1.endswith('gmail.com')) # True
print(email_2.endswith('gmail.com')) # False