# -*- coding: utf-8 -*-
"""StringList.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UM-EuxHcFrFao5bFGidb_yCDlU3EmCy2
"""

template = 'Halo, saya %s dari%s'

print(template % ('Lendis Fabri', 'Indonesia'))

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'Lendis Fabri', asal = 'Indonesia'))
print(template_2.format('Nasi Goreng', 'air putih'))

nama = 'Lendis Fabri'
asal = 'Indonesia'

print(f'Perkenalkan saya {nama} dari {asal}')

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

print('❤'.join(['aku', 'suka', 'python']))

print('😿'.join(alamat.split(',')))

print('halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())

print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

# Mengubah String menjadi Reverse Case

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

# Mencari Kata Pada String

angka = '12345'
print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

# Mereplace Kata pada String

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', '😿'))
print(ibu_kota.replace('a', ''))

# Menghitung Jumlah Karakter yang Muncul

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'Kata "di" muncul sebanyak {x} kali')

