# -*- coding: utf-8 -*-
"""Tipedatacasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wt7AyCmGLaqBx-bntL2wTp9TdVPjoPhX
"""

# Tipe data casting

nama = 'Lendis Fabri'

# Memeriksa Jenis Tipe data

nama = 'Budi'
usia = '29'
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

# Konversi Tipe Data

usia = input('Masukan usia anda:')

print(type(usia))

# Konversi Tipe Data Secara Implisit

a = 10/2
print(type(a))

b = 1/2
print(type(b))

# Konversi Tipe Data Secara Implisit

kata = 'Jeruk' * 5

print(kata)
print(type(kata))

# Konversi String ke Numerik

panjang = int(input('Masukan panjang'))
lebar = int(input('Masukan lebar'))

print('Luas =', panjang * lebar)

# Konversi Numerik ke String

nama = 'Budi'
tahun_lahir = 2001

print(nama + ' lahir di tahun ' + str(tahun_lahir))