# -*- coding: utf-8 -*-
"""TUGAS KELOMPOK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164jt2eZmuWs0-aSQdYcQJ7MkpWNSabRQ
"""

data_kotor = " #001-wahyu aji-informatika-python,java,php-aktif "

# Menghapus spasi di ujung dan karakter '#' di awal (strip & replace).
data = data_kotor.strip()
data = data.replace("#", "")

# Memecah string menjadi list berdasarkan tanda pemisah '-' (split).
pisah = data.split("-")

# Mengambil data
id = pisah[0]
nama = pisah[1]
jurusan = pisah[2]
skill = pisah[3]
status = pisah[4]

# Mengolah daftar skill/hobi (split & join).
list_skill = skill.split(",")
skill_gabung = " & ".join(list_skill)

# Menghitung panjang ID dan jumlah skill (len & count).
panjang_id = len(id)
jumlah_skill = skill.count(",") + 1

# output
print( f"Data Mentah: '  {data_kotor}  '")
print()
print("==============================")
print("    HASIL VERIFIKASI DATA     ")
print("==============================")
print(f"""ID Pendaftar   : {id} ({panjang_id} digit)
Nama Lengkap   : {nama.title()}
Program Studi  : {jurusan.upper()}
Skill Dikuasai : {skill_gabung.lower()}
Total Skill    : {jumlah_skill}
Status Akun    : {status.capitalize()}
==============================""")